language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
    
services:
  - mysql
  
mysql:
  database: yetiforce
  username: root
  encoding: utf8
  
before_script:
- if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-add tests/travis.php.ini; fi
- if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then cat tests/travis.php.ini >> /etc/hhvm/php.ini; fi
- sudo wget https://phar.phpunit.de/phpunit.phar
- sudo chmod +x phpunit.phar
- sudo mv phpunit.phar /usr/local/bin/phpunit
- phpunit --version
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION'"
- mysql -e "create database IF NOT EXISTS yetiforce;" -uroot
- cp tests/copy/config.inc.php config/config.inc.php
- cp tests/copy/debug.php config/debug.php
- cp tests/.htaccess .htaccess
  
script:
- cd tests
- phpunit --debug --verbose --coverage-text --coverage-clover=coverage.clover
    
after_success:
- cat LoginPage.txt
- cat DetailView.txt
- cat ListView.txt
- cat EditView.txt
- bash <(curl -s https://codecov.io/bash) 
- codecov

branches:
  only:
    - developer
